### ISSUE TITLE
getting an error with example.

### ISSUE THREAD

**Issue by geoherna** [secsy/goftp#16]
Whenever I try to use goftp with the provided examples, I get the error message below despite the fact that I am importing:
import "github.com/secsy/goftp"

Screenshot:
http://oi68.tinypic.com/ih5x8n.jpg

Any ideas what might be wrong?

**Comment by geoherna** [comment]
Apologies, closed on accident.

**Comment by muirmanders** [comment]
The examples are within the goftp package, so they omit the goftp package identifier. To use e.g. `DialConfig` you need to do `goftp.DialConfig(...)`.

**Comment by geoherna** [comment]
Yes, I was able to figure this out a little while ago, apologies for not closing ticket.
