### ISSUE TITLE
goftp tests FAIL

### ISSUE THREAD

**Issue by rvicentiu** [secsy/goftp#18]
for anyone reading 

1. do not put goftp in /root as the tests will FAIL
2. edit build_test_server.sh and replace curl -O http://download.pureftpd.org... with curl -k -O https://download.pureftpd.org...
3. if you ran build_test_server.sh as root:
    *  edit ftpd/users.txt and replace uid & gid (now 0:0) with numbers above 1000 (eg 1001:1001)
    * run chown -R 1001:1001 testroot (replace 1001:1001 with your numbers)
    *  in ./ftpd run pure-ftpd-1.0.36/src/pure-pw mkdb users.pdb -f users.txt

tests should now work

**Comment by muirmanders** [comment]
Thanks for opening an issue. By "root goftp directory" the instructions mean the root directory of the project wherever you cloned it to, not /root. I admit it could be worded better. You should not need to run the build_test_server.sh script as root (I set up all the configuration to work as an unprivileged user). The README could probably do with some improvements, so feel free to open a PR with any fixes, or I'll get around to it sometime later.

Why is the `-k` flag needed? Seems like they serve the downloads over HTTPS now which is good, but they have a valid cert so we shouldn't need `-k`.

**Comment by rvicentiu** [comment]
I know, I just wanted to clarify as the ftp servers would not start when "testroot" is within /root (I was lazy and cloned it in /root)
On a dev system I usually run things directly as root so I ran into that issue (Everything was ok when I switched to a unprivileged user).

yes but the local system might have the root certificate needed for validation (older distro)

**Comment by rvicentiu** [comment]
done, check out my pull request
