### ISSUE TITLE
Retrieve as a readable stream ?

### ISSUE THREAD

**Issue by mickael-kerjean** [secsy/goftp#33]
Hello,

First of all, thank you for making this, connection pooling is the killer feature I needed goftp.
Looking at:
```
func (c *Client) Retrieve(path string, dest io.Writer) error
```
my library needs to return an `io.Reader` but I'm not sure which approach would be the best (I'm migrating [this project](https://github.com/mickael-kerjean/nuage) to golang) . 

Now I got something like this:
```
func (f Ftp) Cat(path string) (io.Reader, error) {
	pr, pw := io.Pipe()
	go func() {
		if err := f.client.Retrieve(path, pw); err != nil {
			pr.CloseWithError(NewError("Problem", 409))
		}
		pw.Close()
	}()
	return pr, nil
}
```
But the draback is it's a dirty hack :/

The buffer approach is working fine but would be too taxing in term of RAM. 

Can you advice? I've been spending hours on this already and can't find an efficient solution that's using both stream and proper error handling

**Comment by muirmanders** [comment]
The only way to get the actual reader is to call `OpenRawConn` and initiate the transfer yourself (see below example). The reader/writer in `Retr` is inverted so goftp can automatically retry failed transfers when writing to a file. I don't think using a pipe to invert the writer is a hack.

```
rawConn, _ := client.OpenRawConn()

dcGetter, _ := rawConn.PrepareDataConn()

rawConn.SendCommand("RETR foo.txt")

// get actual data connection (this is your reader)
dc, _ := dcGetter()

data, _ := ioutil.ReadAll(dc)

// close data connection
dc.Close()

// read final response from server after data transfer
rawConn.ReadResponse()
```
