### ISSUE TITLE
unexpected response: 550-SSL/TLS required on the control channel (go lang)(Please help me out )

### ISSUE THREAD

**Issue by avvaripawan** [secsy/goftp#58]
ftpconfig := goftp.Config{

		User:     "*****",
		Password: "*****",
		TLSMode:  0,
	}

	fmt.Println(ftpconfig)

	client, err := goftp.DialConfig(ftpconfig, "******")  # In place of stars i am giving Ip address
	if err != nil {
		fmt.Println(err)
	}
	defer client.Close()

	fmt.Println("connected to ftp server successfully!!!")
	filename := []string{}

	dir, err := client.ReadDir("/")
	if err != nil {
		fmt.Println(err)
	}
	c := 0
	fmt.Println(c, dir, filename)

my output :

connected to ftp server successfully!!!
unexpected response: 550-SSL/TLS required on the control channel
0 [] []

**Comment by jwatson-gcu** [comment]
You need to provide a TLSConfig:
```
dialConfig := goftp.Config{
	User:      "User",
	Password:  "Password",
	TLSMode:   goftp.TLSExplicit,
	TLSConfig: &tls.Config{
		MinVersion: tls.VersionTLS12,
		NextProtos: []string{"http/1.1"},
		ServerName: strings.Split(addr, ":")[0],
	},
}
```

**Comment by avvaripawan** [comment]
jwatson-gcu  thank for the update . But still i am getting error .I applied above snippet

ftpconfig := goftp.Config{

		User:     "******",
		Password: "******",
		TLSMode:  goftp.TLSExplicit,
		TLSConfig: &tls.Config{
			MinVersion: tls.VersionTLS12,
			NextProtos: []string{"http/1.1"},
			ServerName: strings.Split("*****", ":")[0],      #### in place of star i have taken ip addres like 34.89.17.98:21
		},
	}

	fmt.Println(ftpconfig)

	client, err := goftp.DialConfig(ftpconfig, "*****")    ####here also same 
	if err != nil {
		fmt.Println(err)
	}
	defer client.Close()

error: 
connected to ftp server successfully!!!
error writing command: tls: server selected unsupported protocol version 301
[]

> You need to provide a TLSConfig:
> 
> ```
> dialConfig := goftp.Config{
> 	User:      "User",
> 	Password:  "Password",
> 	TLSMode:   goftp.TLSExplicit,
> 	TLSConfig: &tls.Config{
> 		MinVersion: tls.VersionTLS12,
> 		NextProtos: []string{"http/1.1"},
> 		ServerName: strings.Split(addr, ":")[0],
> 	},
> }
> ```

**Comment by jwatson-gcu** [comment]
The error indicates that the server you are connecting to does not support TLS 1.2 i.e. `MinVersion: tls.VersionTLS12`

Remove `MinVersion` from `tls.Config` and give it a try.

**Comment by avvaripawan** [comment]
thank's for the update
