### ISSUE TITLE
Active Mode not supported？

### ISSUE THREAD

**Issue by CodyGuo** [secsy/goftp#7]
Hi,

Can you confirm that active mode is not supported?

Will it be supported in the future?

**Comment by muirmanders** [comment]
Active mode is not supported. Can you help me understand why passive mode doesn't work in your case?

**Comment by CodyGuo** [comment]
The firewall only opened the ports 21, so can only choose to active mode.

**Comment by muirmanders** [comment]
I'm working on this functionality. Hopefully I'll have something this weekend for you to try.

**Comment by CodyGuo** [comment]
Thank you for your help.I'm looking forward to.

**Comment by muirmanders** [comment]
Please try b39bbb226a44170585e2a38e315a869ed7f92abd on the active-transfer-support branch and let me know if it works for you.

**Comment by CodyGuo** [comment]
Please forgive me, I these two days outside on a business trip, two days after the test, have the results immediately feedback.Thank you again for your help.

**Comment by muirmanders** [comment]
你好像是中国人。我帮你弄主动模式，你帮我练中文怎么样？

**Comment by muirmanders** [comment]
请用 b7a28fc1a745921c25ce5d672997912167b5bdde。我修改了主动模式在linux上的问题。

我也发现我忘了告诉你怎么换主动模式。在你的goftp.Config里，加ActiveTransfers: true就行。

**Comment by muirmanders** [comment]
Merged in #10.

**Comment by CodyGuo** [comment]
是中国人，多谢了。但我要怎么帮您练习中文呢？

**Comment by muirrn** [comment]
哈哈开玩笑，不用做什么。再发现不足之处就直接用中文提交issue吧

**Comment by CodyGuo** [comment]
好的，谢谢。

**Comment by muirmanders** [comment]
有了机会在你的环境里试用主动模式的功能吗？

**Comment by CodyGuo** [comment]
已经测试好了，谢谢。
